### ISSUE TITLE
Idea: Workflow for searching and playing items from Spotify

### ISSUE THREAD

**Issue by baschny** [100hz/dopebot#1]
Basic search and returns numbered results for later reference:

* `search <keyword>` returns hits from album, artist, track, playlists
* `search playlist <keyword>` only returns hits from playlists
* `search <type> <keyword>` where type is `album`, `artist`, `playlist`, `track`

For "generic" searches, the "top 10" search results are displayed grouped by type to fill up 10 hits, something like:

```
1. Artist: xyz
2. Artist: xyz #2
3. Album: xyz from artist-name
4. Album: xyz #2 from artist-name
5. Playlist: xyz Playlist 1 from User xy
6. Playlist: xyz Playlist 2 from User zz
7. Track: yzs from artist-name (Album: xxx)
8. Track: yzs from artist-name (Album: xxx)
9. Track: yzs from artist-name (Album: xxx)
10. Track: yzs from artist-name (Album: xxx)
```

Challenge is how to group the different kind of items in this list, and how many of which to display. The spotify client does a pretty good job here.

Then I move over to playing one of the hits:

* `play 5` would then start playing the playlist "xyz Playlist 1 from User xy" 
* `play 1` would play the "top 10" songs from artist xyz
* `play 3` would play the album from 1-end

The same could be used to fill up the "playlist":

* `queue 5`
* `queue 1` 
* etc

Then some commands to be able to see the currently played song + the next 10 songs in the queue:

* `queue show`

.... more to come

**Comment by 100hz** [comment]
👍, thank you mate

**Comment by baschny** [comment]
Done!
