### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by MichaelMallett** [100hz/dopebot#10]
There's really not enough information about what is required to get this running, in terms of setting up in Slack. Even if this is based on another bot (hubot?) it would be helpful to mention that in order to reference other documentation

I get missing scope errors, but I don't know what scope is required. A few lines on the general setup in Slack would go a long way to making this easier. I'll try to write up what I find as I go.

Also, for example, error messages could be more helpful by mentioning what authentication error is generated, ie "Something went wrong when retrieving an access token" would be helpful if it was prefixed with Spotify/Slack.

**Comment by 100hz** [comment]
Hey @MichaelMallett,

sorry for the delay, i just released v1.0.0 of dopebot. The following scopes are required:

* chat:write:bot
* bot
* links:write

![Screenshot 2019-04-07 at 12 58 57](https://user-images.githubusercontent.com/381831/55682534-34791500-5935-11e9-9988-c945c6da18a9.png)

Best Regards,
Sebastian
