### ISSUE TITLE
Better "tracks" listing (Limit to the next 10 and show time to play)

### ISSUE THREAD

**Issue by baschny** [100hz/dopebot#2]
Some cosmetics in the current track list (`tracks`):
- to avoid spamming the channel with too much noise (some playlists have 1000's songs), limit the output of `tracks` to the next 10. If there are more than 10 tracks in the queue, finalize with:

> ... and **YY** more tracks
- prefix the tracks with a number to make the list more readable.

> 1. Track 1 by XY from xxxx
> 2. Track 2 by ZZ from nnnn
> 3. Track 3 by jj from mmm
- if  possible, show the amount of time of music that is enqueued at the end:

> **Total time of music in queue:** hh:mm

**Comment by baschny** [comment]
And additionally it would be neat to see where the tracks from the queue came from:

> From **playlist XY**, added by **Ernesto**:
> 1. Track 1 by XY from xxxx
> 2. Track 2 by ZZ from nnnn
> 3. Track 3 by jj from mmm
> From **album ABC**, added by **Sebastian**:
> 4. Track xxx ...
> ...

But maybe that's too complex... Are "playlist" tracks added randomly or in the same order as the playlist?

**Comment by 100hz** [comment]
@baschny yes, did some refactoring for *tracks* cmd. Please see https://github.com/100hz/dopebot/commit/3d1c888a0f6d1180edbea6a2cdfb3f76b46a5d95

Second part seems to be too complicated at the moment, maybe we add more user-sensitive logic later.
