### ISSUE TITLE
Cosmetics in "search" output

### ISSUE THREAD

**Issue by baschny** [100hz/dopebot#3]
Some improvements in the search output:

* Too many hits! I would only show "maximum 16" and not 10 per category. So if there are enough hits, show 4 artists, 4 albums, 4 playlists, 4 tracks. If one needs more hits in a certain category, search specifically. If there are less hits in one category, fill up "tracks" categories (fallback to playlists, albums) instead. I.e. if there are only 2 artists: show 2 artists, 4 albums, 4 playlists, 6 tracks. etc. 

* Albums hits: Also show artist (and maybe release year?):

> **Master of Puppets** from *Metallica* (1986)

* Tracks hits: Use same output as in the `tracks` list. Maybe add the album in which the track is in, if the information is available without further queries?

* Playlist hits: Also show creator and maybe amount of followers

> **Metallica Greatest Hits** from *hif.pettersson* (8.576 followers)

**Comment by 100hz** [comment]
@baschny Did dome tweaks in the template, as you can see in https://github.com/100hz/dopebot/commit/04a2587a7e0e84f3b67f0eca648dae505d00db33

Strange, but the Spotify API does not give the artist for an album query. So any more information would have need to be extra queried. At least i the links to Spotify are present now, so one can learn more.

Also set the default Spotify search limit to 4.
