### ISSUE TITLE
More infos in "status" output

### ISSUE THREAD

**Issue by baschny** [100hz/dopebot#4]
While playing a playlist, `status` only says "playing". Cool would be to get more infos and maybe add the `current` and `vol` information to it so that this is the one command to see everything about what's going on (less spams in the channel):

> The queue still has **NN** songs - **hh:mm** to go
> Currently playing **Deep Sphere (Stephan Koenigk Remix)** by **Michael Schwarz** from **Deep Sphere EP**
> Volume: 100

So 1. the state of the queue, 2. the current state + song, 3. the current volume 

For 1. the state of the queue, alternatives output in other situations could be:

> This is the last song in the queue
> 
> The queue is empty

For 2. the current state, alternatives:

> Currently paused
> 
> Currently stopped

**Comment by baschny** [comment]
One nice addition would be that on status **change** the current slack channel **title** is updated with the information! Suggestion:

> Playing **Deep Sphere (Stephan Koenigk Remix)** by **Michael Schwarz** from **Deep Sphere EP** (Vol: 100)

So everybody sees current volume and song name right away without having to type any command.

**Comment by 100hz** [comment]
@baschny yes status change is implemented.
