### ISSUE TITLE
Search results numbered throughout types

### ISSUE THREAD

**Issue by baschny** [100hz/dopebot#6]
Currently you search and get hits "0-4" in every type. This requires then to specify the type when wanting to play something. Better would be to number them throughout types and then "play 7" would play that item, regardless of the type:

```
Tracks:
1. 
2. 
3.
4. 
Albums:
5.
6.
7.
Playlists:
8.
9.
10.
```

This seems to be the most common mistake (people typing `play 0`) and would be mitigated by this change.

**Comment by 100hz** [comment]
@baschny ja, good idea

**Comment by 100hz** [comment]
@baschny this is fixed now...hopefully
