### ISSUE TITLE
`play` doesn't clear playlist first

### ISSUE THREAD

**Issue by baschny** [100hz/dopebot#7]
The difference between `play` and `queue` should be that `play` starts the selected item directly (erasing the current list of tracks) and `queue` should just add it for later playing. It seems that currently the `play` also only enqueues, which always require a `clean` before. So the `play` functionality should be fixed or changed.

**Comment by 100hz** [comment]
@baschny yes, **play with reference clears the tracklist**. That is already implemented. But the plain play command simply starts the current track from new, it is the good twin of the **stop** command. I think the bot's output _Adding xy to tracklist_ is a little bit misleading. The tracklist clearing does not trigger any output.

**Comment by baschny** [comment]
That's not what happend today:

> Ernesto Baschny [12:31]  
> search phat rock afternoon
> 
> dopebot BOT [12:31]  
> *Albums:*
> *Nothing found*
> 
> *Artists:*
> *Nothing found*
> 
> *Tracks:*
> *Nothing found*
> 
> *Playlists:*
> 0: *phat rock afternoon/evening* by *22i7xoermnczqupaajrjg4vmy*
> 
> Ernesto Baschny [12:31]  
> play playlist 0
> 
> dopebot BOT [12:31]  
> *Adding spotify:user:22i7xoermnczqupaajrjg4vmy:playlist:5TssY1eILr6UR15NWvOX39 to tracklist*
> 
> [12:31]  
> Track: *Dark Ages* by *Thomas Bergersen* from *SkyWorld*
> State: *playing* | Volume: *10* | Consume: *false* | Random: *true* | Repeat: *false* | Single: *false*
> Initiator: *ingomueller* 30 minutes ago

So my `play playlist 0` did not really cleaned the tracklist, but instead continued to play the tracks added by ingo before (state was "stopped").

Only after a `clear` it worked as expected:

> Ernesto Baschny [12:32]  
> clear
>
> Ernesto Baschny [12:32]  
> play playlist 0
> 
> dopebot BOT [12:32]  
> *Adding spotify:user:22i7xoermnczqupaajrjg4vmy:playlist:5TssY1eILr6UR15NWvOX39 to tracklist*
> 
> [12:32]  
> Track: *Beverly Hills* by *Weezer* from *Make Believe*
> State: *playing* | Volume: *10* | Consume: *false* | Random: *true* | Repeat: *false* | Single: *false*
> Initiator: *ernesto* a few seconds ago

**Comment by 100hz** [comment]
@baschny hmm, it is definitely calling the API for clearing the tracklist: https://github.com/100hz/dopebot/blob/master/lib/commands.js#L46

But yes, also saw some strange behaviour with the clear tracklist command. In the above case i assume, that mopidy was just changing the track, before you command was handled.
