### ISSUE TITLE
Getting unauthenticated errors when searching with 0.3.0

### ISSUE THREAD

**Issue by jak** [100hz/dopebot#8]
I've added a client ID and secret (using https://www.mopidy.com/authenticate/#spotify ) however searching is still unsuccessful.

Will the client id + secret created via the mopidy website work in this context?

**Comment by 100hz** [comment]
Hey @jak,

please update to `dopebot@0.3.4` and create a spotify app via https://developer.spotify.com/my-applications/ to retrieve **clientId** and **secret**!

Best Regards
Sebastian

**Comment by jak** [comment]
Works great, thank you!
