### ISSUE TITLE
search command no longer works

### ISSUE THREAD

**Issue by nistath** [100hz/dopebot#9]
Whenever I do a `search stuff` command on the slack channel this is printed in console:
```
2017-11-07T06:07:46.2222 - error: Something went wrong when retrieving an access token
{ [WebapiError: Bad Request] name: 'WebapiError', message: 'Bad Request', statusCode: 400 }
```

The bot works fine with `play <spotifyuri>` and everything else. It just can't search.

**Comment by baschny** [comment]
@nistath try to follow this tip: https://github.com/100hz/dopebot/issues/8#issuecomment-326952030

Does it work?

**Comment by nistath** [comment]
Yep, apparently the issue is that I used the mopidy app keys instead of a normal app.

7 Νοε 2017, 03:14, ο χρήστης «Ernesto Baschny <notifications@github.com<mailto:notifications@github.com>>» έγραψε:


@nistath<https://github.com/nistath> try to follow this tip: #8 (comment)<https://github.com/100hz/dopebot/issues/8#issuecomment-326952030>

Does it work?

**Comment by MichaelMallett** [comment]
I have the correct access token but search returns nothing. When I look, the app is actually including 'search' in the search string?
```

Searching for "search Moderat" in types:
[ 'album', 'artist', 'track', 'playlist' ]
```

**Comment by 100hz** [comment]
Please refer to the official Spotify documentation: https://developer.spotify.com/dashboard/

You need **Client-ID** and **Client-Secret** which have to be passed to the dopebot command as arguments.
